[versions]
java = "17"
checkstyle = "10.12.5"
jacoco = "0.8.11"
junit = "5.10.1"
spotbugs = "4.8.2"

[plugins]
spotbugs = { id = "com.github.spotbugs", version = "6.0.2" }
versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }

[libraries]
assertJ = "org.assertj:assertj-core:3.24.2"
commonsIO = "commons-io:commons-io:2.15.1"
cthingAnnots = "org.cthing:cthing-annotations:1.0.0"
equalsVerifier = "nl.jqno.equalsverifier:equalsverifier:3.15.4"
freemarker = "org.freemarker:freemarker:2.3.32"
jacksonDatabind = "com.fasterxml.jackson.core:jackson-databind:2.16.0"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = "org.junit.platform:junit-platform-launcher:1.10.1"
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
spotbugsContrib = "com.mebigfatguy.sb-contrib:sb-contrib:7.6.3"
