[versions]
java = "17"
checkstyle = "10.13.0"
jacoco = "0.8.11"
junit = "5.10.2"
spotbugs = "4.8.3"

[plugins]
spotbugs = { id = "com.github.spotbugs", version = "6.0.7" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }

[libraries]
assertJ = "org.assertj:assertj-core:3.25.3"
commonsIO = "commons-io:commons-io:2.15.1"
commonsText = "org.apache.commons:commons-text:1.11.0"
cthingAnnots = "org.cthing:cthing-annotations:1.0.0"
equalsVerifier = "nl.jqno.equalsverifier:equalsverifier:3.15.6"
freemarker = "org.freemarker:freemarker:2.3.32"
jacksonDatabind = "com.fasterxml.jackson.core:jackson-databind:2.16.1"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = "org.junit.platform:junit-platform-launcher:1.10.2"
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
spotbugsContrib = "com.mebigfatguy.sb-contrib:sb-contrib:7.6.4"
